#!/bin/bash
mkdir build
cd build

cmake ${CMAKE_ARGS} -DBACKWARD_TESTS=True -DCMAKE_PREFIX_PATH=$PREFIX -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
make -j${CPU_COUNT}
if [[ "${CONDA_BUILD_CROSS_COMPILATION:-}" != "1" || "${CROSSCOMPILING_EMULATOR}" != "" ]]; then
ctest -V
fi
make install
