{% set name = "backward-cpp" %}
{% set version = "1.6" %}
{% set sha256 = "c654d0923d43f1cea23d086729673498e4741fb2457e806cfaeaea7b20c97c10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/bombela/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - elfutils  # so that the tests compiled in the build step can link to libdw

test:
  requires:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - elfutils

about:
  home: https://github.com/bombela/backward-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Backward is a beautiful stack trace pretty printer for C++.
  doc_url: https://github.com/bombela/backward-cpp/blob/master/README.md
  dev_url: https://github.com/bombela/backward-cpp

extra:
  recipe-maintainers:
    - edisongustavo
    - bombela
