{% set name = "backward-cpp" %}
{% set version = "1.4" %}
{% set sha256 = "ad73be31c5cfcbffbde7d34dba18158a42043a109e7f41946f0b0abd589ed55e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/bombela/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  skip: True  # [not linux]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - elfutils  # so that the tests compiled in the build step can link to libdw

test:
  requires:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - elfutils

about:
  home: https://github.com/bombela/backward-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Backward is a beautiful stack trace pretty printer for C++.'
  doc_url: https://github.com/bombela/backward-cpp/blob/master/README.md
  dev_url: https://github.com/bombela/backward-cpp

extra:
  recipe-maintainers:
    - edisongustavo
    - bombela
