{% set name = "backward-cpp" %}
{% set version = "1.6" %}
{% set sha256 = "c654d0923d43f1cea23d086729673498e4741fb2457e806cfaeaea7b20c97c10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/bombela/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix_tests.patch

build:
  number: 3

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # so that the tests compiled in the build step can link to libdw
    - elfutils  # [linux]

test:
  requires:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - elfutils  # [linux]

about:
  home: https://github.com/bombela/backward-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Backward is a beautiful stack trace pretty printer for C++.
  doc_url: https://github.com/bombela/backward-cpp/blob/master/README.md
  dev_url: https://github.com/bombela/backward-cpp

extra:
  recipe-maintainers:
    - edisongustavo
    - bombela
    - traversaro
